### PR TITLE
add NVRTC_LIB_OVERRIDE

### PR DESCRIPTION
**Pull request by brandonros**
closes https://github.com/coreylowman/cudarc/issues/246

slightly related to https://github.com/coreylowman/cudarc/issues/219

### CODE REVIEW

**Comment by brandonros** [comment]
image

works for me

**Comment by coreylowman** [comment]
I think a more straightforward change would be to add `std::format!("{lib_name}{pointer_width}_{major}0_0"),` to the list of choices under https://github.com/coreylowman/cudarc/blob/6fa8132e87c66efd56c9580235af66559a513d2e/src/lib.rs#L115C9-L115C68.

Just so its consistent with how it works now. 

No idea why windows is so different for cuda world lol.

**Review by coreylowman — CHANGES_REQUESTED** [review]
As I mentioned in the other comment, let's just add another option to the list in `get_lib_name_candidates`, so all the libraries get access to this improvement. No idea what window libs have this issue, so better fix it for all of them pre-emptively.

**Comment by brandonros** [comment]
moving to https://github.com/coreylowman/cudarc/pull/247

**Pull request closed without merging**
