### PR TITLE
support cuda toolkit version: 11.7

### PR DESCRIPTION
**Pull request by wenhaozhao**
This PR adds support for CUDA Toolkit 11.7

### CODE REVIEW

**Comment by corey-lambda** [comment]
This looks great! Just will need to add nccl & cudnn.

You can extract these inside `docker pull nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04` if you don't have access to nccl/cudnn on whatever machine you produced these on!

**Comment by coreylowman** [comment]
This looks great! Just will need to add nccl & cudnn.

You can extract these inside `docker pull nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04` if you don't have access to nccl/cudnn on whatever machine you produced these on!

**Comment by wenhaozhao** [comment]
> This looks great! Just will need to add nccl & cudnn.
> 
> You can extract these inside `docker pull nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04` if you don't have access to nccl/cudnn on whatever machine you produced these on!

ok, thanks!
I've added two files about **nccl** & **cudnn**
- 1 src/cudnn/sys/sys_11070.rs
- 2 src/nccl/sys/sys_11070.rs

**Comment by coreylowman** [comment]
Yay perfect, thanks

**Comment by coreylowman** [comment]
Hmm looks like there were some pretty breaking changes for cudnn/nccl on 11.7 (getting errors when trying to compile for that version in the safe apis). Will need to think about that

**Pull request merged**
